const ErrorCodes = Object.freeze({
  OK: 200,
  VALIDATION_ERROR: 400,
  PARSE_FAILED: 500,
  VIDEO_UNAVAILABLE: 500,
  DOWNLOAD_RESOURCE_MISSING: 500,
  AI_CHAT_FAILED: 500,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500
});

module.exports = ErrorCodes;
