const ErrorCodes = Object.freeze({
  OK: 'OK',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PARSE_FAILED: 'PARSE_FAILED',
  VIDEO_UNAVAILABLE: 'VIDEO_UNAVAILABLE',
  DOWNLOAD_RESOURCE_MISSING: 'DOWNLOAD_RESOURCE_MISSING',
  AI_CHAT_FAILED: 'AI_CHAT_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
});

module.exports = ErrorCodes;
